# Generated by Django 3.2.1 on 2022-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_code', models.CharField(max_length=64, verbose_name='三方物流库代码')),
                ('pl_name', models.CharField(max_length=64, verbose_name='三方物流库名称')),
                ('supply_code', models.CharField(max_length=64, verbose_name='供应商代码')),
                ('supply_name', models.CharField(max_length=64, verbose_name='供应商名称')),
                ('part_code', models.CharField(max_length=64, verbose_name='零件代号')),
                ('part_name', models.CharField(max_length=64, verbose_name='零件名称')),
                ('parts_num', models.BigIntegerField(default=None, max_length=64, null=True, verbose_name='零件数量')),
            ],
        ),
    ]
