# Generated by Django 3.2.1 on 2022-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0002_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_warning', models.CharField(max_length=64, verbose_name='库存报警')),
                ('online_warning', models.CharField(max_length=64, verbose_name='在线报警')),
                ('days_store', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='可持续天数')),
                ('part_universal', models.CharField(choices=[(0, '非通用件'), (1, '通用件')], max_length=64, verbose_name='在线报警')),
                ('part_code', models.CharField(max_length=64, verbose_name='零件号')),
                ('part_name', models.CharField(max_length=64, verbose_name='零件名称')),
                ('plant_code', models.CharField(max_length=16, verbose_name='工厂代码')),
                ('supply_name', models.CharField(max_length=64, verbose_name='供应商名称')),
                ('supply_code', models.CharField(max_length=16, verbose_name='供应商代码')),
                ('person_purchase', models.CharField(max_length=16, verbose_name='筹措员')),
                ('pl_code', models.CharField(max_length=64, verbose_name='三方物流库代码')),
                ('pl_name', models.CharField(max_length=64, verbose_name='三方物流库名称')),
                ('parts_num', models.BigIntegerField(default=None, null=True, verbose_name='库存数量')),
                ('online_stock', models.BigIntegerField(default=None, null=True, verbose_name='在线需求')),
                ('require_max', models.BigIntegerField(default=None, null=True, verbose_name='MAX日需求')),
                ('require_one', models.BigIntegerField(default=None, null=True, verbose_name='Day1需求')),
                ('require_two', models.BigIntegerField(default=None, null=True, verbose_name='Day2需求')),
                ('require_three', models.BigIntegerField(default=None, null=True, verbose_name='Day3需求')),
                ('require_four', models.BigIntegerField(default=None, null=True, verbose_name='Day4需求')),
                ('require_five', models.BigIntegerField(default=None, null=True, verbose_name='Day5需求')),
                ('require_six', models.BigIntegerField(default=None, null=True, verbose_name='Day6需求')),
                ('require_seven', models.BigIntegerField(default=None, null=True, verbose_name='Day7需求')),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='parts_num',
            field=models.BigIntegerField(default=None, null=True, verbose_name='库存数量'),
        ),
    ]
