# Generated by Django 3.2.1 on 2022-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0004_auto_20220910_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorypartsdata',
            name='parts_loci',
        ),
        migrations.AddField(
            model_name='factorypartsdata',
            name='person_purchase',
            field=models.CharField(default=None, max_length=16, verbose_name='筹措员'),
        ),
        migrations.AddField(
            model_name='factorypartsdata',
            name='plant_code',
            field=models.CharField(default=None, max_length=16, verbose_name='工厂代码'),
        ),
        migrations.AddField(
            model_name='factorypartsdata',
            name='tpl_code',
            field=models.CharField(default=None, max_length=16, verbose_name='三方物流代码'),
        ),
        migrations.AddField(
            model_name='factorypartsdata',
            name='tpl_name',
            field=models.CharField(default=None, max_length=32, verbose_name='三方物流名称'),
        ),
        migrations.AlterField(
            model_name='factorypartsdata',
            name='part_code',
            field=models.CharField(default=None, max_length=24, verbose_name='零件代号'),
        ),
        migrations.AlterField(
            model_name='factorypartsdata',
            name='part_name',
            field=models.CharField(default=None, max_length=24, verbose_name='零件名称'),
        ),
        migrations.AlterField(
            model_name='factorypartsdata',
            name='supply_code',
            field=models.CharField(default=None, max_length=16, verbose_name='供应商代码'),
        ),
        migrations.AlterField(
            model_name='factorypartsdata',
            name='supply_name',
            field=models.CharField(default=None, max_length=16, verbose_name='供应商名称'),
        ),
    ]
