# Generated by Django 3.2.1 on 2022-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0005_auto_20220910_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydata',
            name='parts_num',
        ),
        migrations.AddField(
            model_name='inventorydata',
            name='tpl_number',
            field=models.BigIntegerField(default=None, null=True, verbose_name='3PL库存'),
        ),
    ]
