# Generated by Django 3.2.1 on 2022-09-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0006_auto_20220910_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydata',
            old_name='pl_code',
            new_name='tpl_code',
        ),
        migrations.RenameField(
            model_name='inventorydata',
            old_name='pl_name',
            new_name='tpl_name',
        ),
    ]
