# Generated by Django 3.2.1 on 2022-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0007_auto_20220910_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydata',
            name='online_warning',
            field=models.CharField(default=None, max_length=64, verbose_name='在线报警'),
        ),
        migrations.AlterField(
            model_name='inventorydata',
            name='store_warning',
            field=models.CharField(default=None, max_length=64, verbose_name='库存报警'),
        ),
    ]
